rabbitmq:
  image: rabbitmq:3-management
mysql: 
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: donotuse
    MYSQL_DATABASE: ctdata
    MYSQL_USER: ctdata
    MYSQL_PASSWORD: use_this_password
raspnodea:
  build: ./raspnode-1/
raspnodeb:
  build: ./raspnode-2/
sensorgateway:
  build: ./sensorgateway/
  links:
  - rabbitmq
  - raspnodea
  - raspnodeb
orchestrator:
  build: ./orchestrator/
  links:
  - rabbitmq
datanode:
  build: ./datanode/
  links:
  - mysql
  - rabbitmq
webapp:
  build: ./webapp/
  links:
  - rabbitmq
  ports:
  - "80:8080"